name: Main workflow

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml 4.14.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x

      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune runtest
      - run: opam exec -- dune build

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: align.exe
          path: _build/default/bin/main.exe

